# Generated by Django 4.1.7 on 2023-04-01 22:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('id_no', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'Only alphanumeric characters are allowed.')])),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField(validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numbers are allowed.')])),
                ('address', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'Only alphanumeric characters are allowed.')])),
                ('ssnit_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'Only alphanumeric characters are allowed.')])),
                ('jobs', models.CharField(choices=[('WH', 'Warehouse Manager'), ('WS', 'Warehouse Supervisor'), ('L', 'Loader'), ('DEO', 'Data Entry Officer'), ('D', 'Driver'), ('C', 'Cleaner')], default='WH', max_length=3)),
                ('Guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.guarantor')),
            ],
        ),
    ]
