# Generated by Django 4.1.7 on 2023-04-07 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_first_name_employee_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarantor',
            name='phone',
        ),
        migrations.AddField(
            model_name='guarantor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')]),
        ),
    ]
