# Generated by Django 4.1.7 on 2023-04-07 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_employee_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor',
            name='id_no',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
