# Generated by Django 4.1.7 on 2023-04-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_guarantor_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='jobs',
            field=models.CharField(choices=[('WH', 'Warehouse Manager'), ('WS', 'Warehouse Supervisor'), ('L', 'Loader'), ('DEO', 'Data Entry Officer'), ('C', 'Cleaner')], default='WH', max_length=3),
        ),
    ]
